Taskkill /F /IM SCRIPTTOOL.EXE
Taskkill /F /IM dataview.exe
Taskkill /F /IM dl1131.exe
Taskkill /F /IM techview.exe
Taskkill /F /IM loclview.exe
Taskkill /F /IM bservice.exe
Taskkill /F /IM bsipdrv.exe
Taskkill /F /IM resmon.exe
Taskkill /F /IM bsbsap3s.exe
